/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_sesion4;

public class Combustible extends javax.swing.JPanel {
    
    float combustible;
    EstadoMotor estado;
    double revoluciones;

    /**
     * Creates new form Combustible
     */
    public Combustible() {
        initComponents();
        combustible = (float)100.0;
        estado = EstadoMotor.APAGADO;
        revoluciones = 0.0;
        radial1Square1.setValue(combustible);
    }
    
    public boolean ejecutar(double revoluciones, EstadoMotor estadoMotor){
        if (estadoMotor != EstadoMotor.APAGADO){
            combustible -= revoluciones / 10000.0;
            if (combustible < 0){
                combustible = (float)0.0;
            }
        }
        
        estado = estadoMotor;
        this.revoluciones = revoluciones;
        radial1Square1.setValueAnimated(combustible);
        
        if (combustible <= 20.0){
            radial1Square1.setLedBlinking(true);
        } else{
            radial1Square1.setLedBlinking(false);
        }
        
        this.repaint();
        this.revalidate();
        return (combustible > 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        radial1Square1 = new eu.hansolo.steelseries.gauges.Radial1Square();

        jButton1.setBackground(new java.awt.Color(1, 1, 1));
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Repostar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        radial1Square1.setTitle("Combustible");
        radial1Square1.setUnitString("%");

        javax.swing.GroupLayout radial1Square1Layout = new javax.swing.GroupLayout(radial1Square1);
        radial1Square1.setLayout(radial1Square1Layout);
        radial1Square1Layout.setHorizontalGroup(
            radial1Square1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        radial1Square1Layout.setVerticalGroup(
            radial1Square1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radial1Square1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(radial1Square1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (estado == EstadoMotor.APAGADO && revoluciones == 0.0)
            combustible = (float)100.0;
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private eu.hansolo.steelseries.gauges.Radial1Square radial1Square1;
    // End of variables declaration//GEN-END:variables
}
