/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_sesion4;

import java.text.DecimalFormat;

public class CuentaKilometros extends javax.swing.JPanel {

    /**
     * Creates new form CuentaKilometros
     */
    
    double reciente;
    double total;
    private static final DecimalFormat df = new DecimalFormat("#.##");
    
    public CuentaKilometros() {
        initComponents();
        reciente = 0.0;
        total = 0.0;

    }
    
    public void ejecutar(double revoluciones, EstadoMotor estadoMotor){
        double v = ((2 * Math.PI * 0.15) * revoluciones * (60.0/1000.0));
        
        if (estadoMotor == EstadoMotor.APAGADO && v == 0.0){
            reciente = 0.0;
            displaySingle3.setLcdValue(reciente);
        }
        
        reciente += v/7200.0;
        total += v/7200.0;
        
        displaySingle3.setLcdValueAnimated(reciente);
        displaySingle4.setLcdValueAnimated(total);
        
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displaySingle1 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        displaySingle2 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        displaySingle3 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        displaySingle4 = new eu.hansolo.steelseries.gauges.DisplaySingle();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(300, 128));

        displaySingle1.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.CUSTOM);
        displaySingle1.setLcdUnitString("KM Recientes");

        displaySingle2.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.CUSTOM);
        displaySingle2.setLcdUnitString("KM Totales");

        displaySingle3.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.CUSTOM);
        displaySingle3.setLcdDecimals(2);
        displaySingle3.setLcdUnitString("KM Actuales");

        displaySingle4.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.CUSTOM);
        displaySingle4.setLcdDecimals(2);
        displaySingle4.setLcdUnitString("KM Totales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displaySingle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displaySingle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(369, 369, 369))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displaySingle3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displaySingle4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displaySingle3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displaySingle4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(displaySingle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displaySingle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.steelseries.gauges.DisplaySingle displaySingle1;
    private eu.hansolo.steelseries.gauges.DisplaySingle displaySingle2;
    private eu.hansolo.steelseries.gauges.DisplaySingle displaySingle3;
    private eu.hansolo.steelseries.gauges.DisplaySingle displaySingle4;
    // End of variables declaration//GEN-END:variables
}
