/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_sesion4;

public class Salpicadero extends javax.swing.JPanel {
    
    GestorFiltros g;

    /**
     * Creates new form salpicaderov2
     */
    public Salpicadero() {
        initComponents();
    }
    
    public void enlazar(GestorFiltros g){
        this.g = g;
    }
    
    public boolean ejecutar(double revoluciones, EstadoMotor estadoMotor, double revolucionesMantenidas, double porcentajeAceite, double revolucionesAceite, 
            double porcentajeFrenos, double revolucionesFrenos, double porcentajeGeneral, double revolucionesGeneral){
        
        velocimetro1.ejecutar(revoluciones, revolucionesMantenidas);
        cuentaRevoluciones2.ejecutar(revoluciones);
        cuentaKilometros1.ejecutar(revoluciones, estadoMotor);
        controladorRevision1.ejecutar(porcentajeAceite, revolucionesAceite, porcentajeFrenos, revolucionesFrenos, porcentajeGeneral, revolucionesGeneral);
        
        
        if (g != null){
            if (controladorRevision1.isCambiarAceite()){
                g.revisarAceite();
            }
            if (controladorRevision1.isCambiarFrenos()){
                g.revisarFrenos();
            }
            if (controladorRevision1.isCambiarGeneral()){
                g.revisarGeneral();
            }
        }
        
        return (combustible1.ejecutar(revoluciones, estadoMotor));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        velocimetro1 = new practica1_sesion4.Velocimetro();
        combustible1 = new practica1_sesion4.Combustible();
        cuentaKilometros1 = new practica1_sesion4.CuentaKilometros();
        cuentaRevoluciones2 = new practica1_sesion4.CuentaRevoluciones();
        controladorRevision1 = new practica1_sesion4.ControladorRevision();

        velocimetro1.setBorder(null);

        combustible1.setBorder(null);

        cuentaKilometros1.setBorder(null);

        cuentaRevoluciones2.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(velocimetro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(cuentaKilometros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuentaRevoluciones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combustible1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(controladorRevision1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(velocimetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cuentaKilometros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(cuentaRevoluciones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(combustible1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(controladorRevision1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private practica1_sesion4.Combustible combustible1;
    private practica1_sesion4.ControladorRevision controladorRevision1;
    private practica1_sesion4.CuentaKilometros cuentaKilometros1;
    private practica1_sesion4.CuentaRevoluciones cuentaRevoluciones2;
    private practica1_sesion4.Velocimetro velocimetro1;
    // End of variables declaration//GEN-END:variables
}
