/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1_sesion4;

import java.math.*;
import java.text.DecimalFormat;

public class Velocimetro extends javax.swing.JPanel {
    
    /**
     * Creates new form Velocimetro
     */
    public Velocimetro() {
        initComponents();
        radial1.setValue(0.0);
    }
    
    public void ejecutar(double revoluciones, double revolucionesMantenidas){
        double v = ((2 * Math.PI * 0.15) * revoluciones * (60.0/1000.0));
        double vGuardada = ((2 * Math.PI * 0.15) * revolucionesMantenidas * (60.0/1000.0));
        radial1.setValue(v);
        displaySingle1.setLcdValue(vGuardada);
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airCompass1 = new eu.hansolo.steelseries.extras.AirCompass();
        radial1 = new eu.hansolo.steelseries.gauges.Radial();
        displaySingle1 = new eu.hansolo.steelseries.gauges.DisplaySingle();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        radial1.setLcdDecimals(2);
        radial1.setMaxValue(280.0);
        radial1.setTitle("Velocidad");
        radial1.setUnitString("km/h");

        javax.swing.GroupLayout radial1Layout = new javax.swing.GroupLayout(radial1);
        radial1.setLayout(radial1Layout);
        radial1Layout.setHorizontalGroup(
            radial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        radial1Layout.setVerticalGroup(
            radial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        displaySingle1.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.CUSTOM);
        displaySingle1.setLcdUnitString("KM Guardados");

        javax.swing.GroupLayout displaySingle1Layout = new javax.swing.GroupLayout(displaySingle1);
        displaySingle1.setLayout(displaySingle1Layout);
        displaySingle1Layout.setHorizontalGroup(
            displaySingle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        displaySingle1Layout.setVerticalGroup(
            displaySingle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(displaySingle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(radial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displaySingle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.steelseries.extras.AirCompass airCompass1;
    private eu.hansolo.steelseries.gauges.DisplaySingle displaySingle1;
    private eu.hansolo.steelseries.gauges.Radial radial1;
    // End of variables declaration//GEN-END:variables
}
